version: '3'

services:
  app:
    container_name: iot-server
    restart: always
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE= iot
    ports:
      - '27017:27017'
    volumes:
      - './mongodb:/data/db'
